line-length = 120
indent-width = 4

[lint]
select = ["S", "A", "FIX", "G", "I", "C90", "N", "E", "W", "D", "F"]
ignore = ["D", "S"]
fixable = ["E", "W"]

[format]
quote-style = 'single'
indent-style = 'space'
